### ISSUE TITLE
False Positive - Table View Cells

### ISSUE THREAD

**Issue by Sherlouk** [woshiccm/Pecker#11]
We have a UITableViewCell class with a corresponding XIB. We register it to the UITableView using `tableView.register(nib, reuseIdentifier)` and dequeue it as per standard implementation.

As the cell class is not directly referenced, a warning is incorrectly raised.

**Comment by woshiccm** [comment]
The same is because there is not enough support for xib and storyboard, it will be resolved as soon as possible, thank you for your feedback

**Comment by woshiccm** [comment]
fixed
