### ISSUE TITLE
Types used as typecasting

### ISSUE THREAD

**Issue by invinciible** [woshiccm/Pecker#14]
Structure Types if used in typecasting while decoding the Data using Codable protocol using "as" keyword creating a warning.

**Comment by woshiccm** [comment]
Will take a look at it, thanks

**Comment by woshiccm** [comment]
Could you show me the code, my English is not very good, so I don’t particularly understand your case.

**Comment by invinciible** [comment]
![Screenshot 2019-12-12 at 5 46 25 PM](https://user-images.githubusercontent.com/25017046/70711392-7994e880-1d07-11ea-95b4-d93347f481a7.png)

Leaves type used on line number 16.

**Comment by woshiccm** [comment]
fixed
