### ISSUE TITLE
Request: Better/configurable error output

### ISSUE THREAD

**Issue by noahsark769** [woshiccm/Pecker#19]
Hey there! I noticed that the fully build `pecker` executable, in default configuration, doesn't output any error logs when run. For example, if you run it on a path that doesn't exist, it will swallow the error and not print anything.

It would be really nice to have a better error logging system to provide feedback to users running the executable, since right now the error state and the "no unused code" state look the same.

**Comment by woshiccm** [comment]
You are right i was thinking the best solution

**Comment by woshiccm** [comment]
Had improved
