### ISSUE TITLE
Request: Blacklist positives with a comment

### ISSUE THREAD

**Issue by noahsark769** [woshiccm/Pecker#20]
We have a few true positives in our codebase which we'd like to keep around since they're not used yet but will _soon_ be used. It would be nice if we could disable the pecker checker with a comment, similar to Swiftlint. Something like:

```
func myUnsusedFunction() { // pecker:ignore
}

// or:

// pecker:ignore:next
func myUnusedFunction() {
  print("Blah")
}
```

**Comment by woshiccm** [comment]
Good suggestion, will improve

**Comment by woshiccm** [comment]
Done, PR is here https://github.com/woshiccm/Pecker/pull/24

**Comment by noahsark769** [comment]
Wow, awesome work! Thanks!
