### ISSUE TITLE
False Positive: SwiftUI Previews

### ISSUE THREAD

**Issue by noahsark769** [woshiccm/Pecker#26]
By default, SwiftUI generates a struct which conforms to `PreviewProvider`, e.g.:

```
import SwiftUI

struct SettingsView: View {
    var body: some View {
        ...
    }
}

#if DEBUG
struct SettingsView_Previews: PreviewProvider {
    static var previews: some View {
        SettingsView()
    }
}
#endif
```

In the default configuration, pecker reports `SettingsView_Previews` as unused. It would be good to add a rule to ignore structs which conform to PreviewProvider.

**Comment by woshiccm** [comment]
Does `static var previews`  also need to ignore?

**Comment by woshiccm** [comment]
Done, PR: https://github.com/woshiccm/Pecker/pull/28

**Comment by noahsark769** [comment]
Thanks!
