### ISSUE TITLE
False Positive: Subclasses of subclasses of XCTestCase

### ISSUE THREAD

**Issue by noahsark769** [woshiccm/Pecker#35]
If you have a subclass of XCTestCase (e.g. a BaseTestCase where you put your generic testing utilities), Pecker currently reports tests that inherit from this subclass these as unused. For example:

```swift
import XCTest

class BaseTestCase: XCTestCase {

}

extension BaseTestCase {
    func a() {
        print("a")
    }
}

class TestCase: BaseTestCase { // currently reported as unused
    func test() { // currently reported as unused
        self.a()
    }
}
```

Working example in repo: https://github.com/noahsark769/NGPeckerExamples/blob/master/NGPeckerExamplesTests/XCTestSuperclassMethodUsedBySubclass.swift#L11

**Comment by woshiccm** [comment]
https://github.com/woshiccm/Pecker/issues/6 
Others have opened a issue, I am still working on it, so this will be closed😂

**Comment by woshiccm** [comment]
https://github.com/woshiccm/Pecker/issues/6

My fault, that issue is not you opened

**Comment by noahsark769** [comment]
Ah oops, you're right! Sorry!
