### ISSUE TITLE
Request: customizable SuperClassRule

### ISSUE THREAD

**Issue by noahsark769** [woshiccm/Pecker#37]
We use Quick for testing, which means that our tests inherit from QuickSpec. Since this isn't supported out of the box, it would be nice for us to be able to ignore all subclasses of Quickspec by default.

It seems the best way would be to make the SuperClassRule customizable via `.pecker.yml` for this.

**Comment by woshiccm** [comment]
Good suggestion

**Comment by woshiccm** [comment]
Done, you can add QuickSpec to blacklist_superclass
