### ISSUE TITLE
False Positive: Test methods in extensions

### ISSUE THREAD

**Issue by AdamPro13** [woshiccm/Pecker#39]
It looks like test methods declared in extensions currently show warnings as false positives despite the `xctest` rule being enabled. The following `testExample()` method shows a warning.

```
class MyTestClass: XCTestCase {
}

extension MyTestClass {
    func testExample() { // This shows a warning as being unused
        XCTAssertTrue(true)
    }
}
```

**Comment by woshiccm** [comment]
Fixed, the version is 0.0.12
