### ISSUE TITLE
Warning for Methods in Protocol when satisfying conformance in extension

### ISSUE THREAD

**Issue by RalfK92** [woshiccm/Pecker#45]
protocol Protocol {
    var variable: Bool { get }
    func function(parameter: String?) -> String?
}

Implementing this Protocol in a class and satisfying conformance in extension works for variable but not for function. 

class Class: Protocol { }

extension Class {
     var variable: Bool { // no warning
             return "Temp"
      }
     
   func function (parameter: String?) -> { // warning
      return parameter
   }
}

**Comment by woshiccm** [comment]
Thanks, will fix it

**Comment by victorrr** [comment]
What is the status with this fix? If you have a lot of protocols you get spammed with false Pecker warnings

**Comment by mthole** [comment]
Used Pecker for the first time today and am loving it. I'm also running into this issue, though, so wanted to chime in and say 'me too'. Thanks for this tool!

**Comment by woshiccm** [comment]
this issue had been resolved in new version 0.4.0
