### ISSUE TITLE
Custom path of configuration file

### ISSUE THREAD

**Issue by oleghnidets** [woshiccm/Pecker#47]
Hi,

First of all, thanks for great tool. Amazing job 💪

I found one missed thing that is nice to have. It is custom path for configuration yaml file. For example, SwiftLint allows it in the following way:

> ${PODS_ROOT}/SwiftLint/swiftlint --config ../.swiftlint.yml

Does it make sense for you? Could you, please, provide something similar?

**Comment by woshiccm** [comment]
Thanks, will take a look at it.Because I've been a bit busy recently, might have to wait a bit

**Comment by woshiccm** [comment]
@oleghnidets Fixed it in version 0.3.0

**Comment by oleghnidets** [comment]
Thank you! 💪
