### ISSUE TITLE
执行命令时报错[1]    85594 illegal hardware instruction  pecker ./ -i ~/E/Z/Lark-awwlhnagktjjwaendjbfipmvwrcf/Index/DataStore

### ISSUE THREAD

**Issue by 3677065** [woshiccm/Pecker#52]
工程下.pecker.yml文件配置：
reporter: "json"
output_file: "~/Jenkins/workspace/lark/ios/app-analyse/ios-client-master-appsize-verify"

输入命令行pecker ~/Jenkins/workspace/lark/ios/app-analyse/ios-client-master-appsize-verify -i ~/E/Z/Lark-awwlhnagktjjwaendjbfipmvwrcf/Index/DataStore，

报错：[1]    85594 illegal hardware instruction  pecker  -i ~/E/Z/Lark-awwlhnagktjjwaendjbfipmvwrcf/Index/DataStore

**Comment by woshiccm** [comment]
同学你是字节飞书的吗，我是字节iOS基础技术部的，可以飞书沟通哈，这两天解决这个问题

**Comment by woshiccm** [comment]
caoming.roy@bytedance.com

**Comment by woshiccm** [comment]
我刚刚测了没问题，你终端open ~/E/Z/Lark-awwlhnagktjjwaendjbfipmvwrcf/Index/DataStore
能打开吗？

**Comment by woshiccm** [comment]
我测试是没有问题的，你可以试试0.3.0版本试试看，另外你是飞书的同学吗？可以飞书私聊我，caoming.roy@bytedance.com
