### ISSUE TITLE
@IBAction false positive

### ISSUE THREAD

**Issue by Sherlouk** [woshiccm/Pecker#7]
`@IBAction func someFunction() {` currently returns a warning, but it is used/called by our UIStoryboard!

**Comment by woshiccm** [comment]
Pecker support Storyboard and xib are not enough, will find a solution as soon as possible, thank you for your feedback

**Comment by Sherlouk** [comment]
I think this is more that anything that is ObjC marked code ([at]IBAction, [at]ObjC etc) should just be ignored as it's almost impossible to reliably check if it's called.

**Comment by woshiccm** [comment]
Yep, I will try my best to find a solution. If still can’t solve it, can only solve it this way.

**Comment by woshiccm** [comment]
fixed
