### ISSUE TITLE
False positive for functions from protocol

### ISSUE THREAD

**Issue by Sherlouk** [woshiccm/Pecker#8]
```
protocol SomeProtocol {
  func doSomething()
}
class Implementation: SomeProtocol {
  func doSomething() { // Warning
  }
}
```

`doSomething` is called from other code via the protocol

**Comment by woshiccm** [comment]
![屏幕快照 2019-12-10 下午9.22.28.png](https://upload-images.jianshu.io/upload_images/2086987-dc2697f5459e3371.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by woshiccm** [comment]
I think maybe xcode have not indexing your code, so when check can't find the symbol of doSomething in IndexStoreDB. Maybe you reopen the project or reopen xcode, the warning will disappear. I occasionally encounter it when debugging, but rarely
