### ISSUE TITLE
False Positive - Extension Principle Class

### ISSUE THREAD

**Issue by Sherlouk** [woshiccm/Pecker#9]
If you have an extension (such as a Notification Service Extension) then you end up with a class called `NotificationService` (this can be changed).

Apple knows to run this because of an entry in the Info.plist "NSExtensionPrincipalClass" which equals "$(PRODUCT_MODULE_NAME).NotificationService".

Pecker is raising a warning for this main class, but it is in fact being used.

**Comment by woshiccm** [comment]
Will take a look at it

**Comment by woshiccm** [comment]
Done, PR: https://github.com/woshiccm/Pecker/pull/28
